### ISSUE TITLE
Research hosting solutions

### ISSUE THREAD

**Issue by mlouage** [XPRTZ/website#2]
Azure seems like a very good candidate since we are .NET developers

1. ⛔ Azure static web app
  👍 Seems like the most straightforward solution.
  👎 Next 14 is not completely supported, only all the static parts.
2. ⛔ Azure storage account + Azure CDN
  👎 A lot of manual work, also custom steps in the pipeline to purge the CDN
  👎 Not sure about the Next 14 export settings, could very well be that only static is supported
3. ⛔ Azure Web App
  👍 It has been there for ages and is supported with next 14 if we change the output to standalone
  👍 We can use GitHub Actions for CI/CD
4. ✅ Azure Container Apps
  ✅ Easy to run locally and deploy 
5. ⛔ Vercel could be a strong contender 
  👍 Minimize friction in deployments, connection with GitHub is OK
  👍 We can still use GitHub Actions for CI
  👎 Vercel requires a Team account (20 USD/user) because we want to deploy from a GitHub Organization.

**Comment by mawax** [comment]
First test on GitHub Actions with Azure was very slow (20+ minutes). Possibly due to this issue: https://github.com/Azure/webapps-deploy/issues/60

**Comment by mlouage** [comment]
Given this fact maybe reconsider just running in a container. Also easy for local development. Running in a container means the same modification to the next config file: output standalone and start command should be next start.
